ent-USSPReagentCanister = канистра
    .desc = Очень большая ёмкость. Не спрашивайте, как она помещается в раздатчик.
ent-USSPReagentCanisterCarbon = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterIodine = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterFluorine = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterChlorine = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterAluminium = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterPhosphorus = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterSulfur = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterSilicon = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterHydrogen = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterLithium = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterSodium = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterPotassium = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterRadium = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterIron = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterCopper = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterGold = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterMercury = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterSilver = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterEthanol = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterSugar = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterNitrogen = канистра
    .desc = { ent-USSPReagentCanister.desc }
ent-USSPReagentCanisterOxygen = канистра
    .desc = { ent-USSPReagentCanister.desc }
