ent-SpawnERTLeaderEVAPreset = спавн лидера ОБР
    .desc = Спавн поинт лидера ОБР
    .suffix = CALLERT
callert-leader-eva-name = Лидер ОБР
callert-leader-eva-desc = Лидер отряда быстрого реагирования.
callert-leader-eva-rules = Ваша задача руководить отрядом специального назначения для выполнения особых целей на станции. Вы подчиняетесь ЦК.
ent-SpawnERTMedicEVAPreset = спавн медика ОБР
    .desc = Спавн поинт медика ОБР
    .suffix = CALLERT
callert-medic-eva-name = Медик ОБР
callert-medic-eva-desc = Медик отряда быстрого реагирования.
callert-medic-eva-rules = Ваша задача оказывать медицинскую помощь членам отряда ОБР. Вы подчиняетесь лидеру ОБР.
ent-SpawnERTSecurityEVAPreset = спавн бойца ОБР
    .desc = Спавн поинт бойца ОБР
    .suffix = CALLERT
callert-security-eva-name = Боец ОБР
callert-security-eva-desc = Боец отряда быстрого реагирования.
callert-security-eva-rules = Ваша задача выполнять поставленные задачи на станции, при необходимости применять силу. Вы подчиняетесь лидеру ОБР.
ent-SpawnERTEngineerEVAPreset = спавн инженера ОБР
    .desc = Спавн поинт инженера ОБР
    .suffix = CALLERT
callert-engineer-eva-name = Инженер ОБР
callert-engineer-eva-desc = Инженер отряда быстрого реагирования.
callert-engineer-eva-rules = Ваша задача в кратчайшие сроки починить разрушения на станции. Вы подчиняетесь лидеру ОБР.
ent-SpawnERTJanitorEVAPreset = спавн уборщика ОБР
    .desc = Спавн поинт уборщика ОБР
    .suffix = CALLERT
callert-janitor-eva-name = Уборщик ОБР
callert-janitor-eva-desc = Уборщик отряда быстрого реагирования.
callert-janitor-eva-rules = Ваша задача в кратчайшие сроки привести станцию в порядок. Вы подчиняетесь лидеру ОБР.
ent-SpawnCBURNLeaderEVAPreset = спавн лидера РХБЗЗ
    .desc = Спавн поинт лидера РХБЗЗ
    .suffix = CALLERT
callert-cburn-leader-eva-name = Лидер РХБЗЗ
callert-cburn-leader-eva-desc = Лидер отряда радио химическо биологическо зомби защиты.
callert-cburn-leader-eva-rules = Ваша задача ликвидировать все последствия катастрофы на станции. Вы подчиняетесь ЦК.
ent-SpawnCBURNSecurityEVAPreset = спавн РХБЗЗ
    .desc = Спавн поинт РХБЗЗ
    .suffix = CALLERT
callert-cburn-security-eva-name = РХБЗЗ
callert-cburn-security-eva-desc = Боец отряда радио химическо биологическо зомби защиты.
callert-cburn-security-eva-rules = Ваша задача ликвидировать все последствия катастрофы на станции. Вы подчиняетесь лидеру РХБЗЗ.
ent-SpawnCBURNMedicEVAPreset = спавн медика РХБЗЗ
    .desc = Спавн поинт медика РХБЗЗ
    .suffix = CALLERT
callert-cburn-medic-eva-name = Медик РХБЗЗ
callert-cburn-medic-eva-desc = Медик отряда радио химическо биологическо зомби защиты.
callert-cburn-medic-eva-rules = Ваша задача ликвидировать все последствия катастрофы на станции. Вы подчиняетесь лидеру РХБЗЗ.
ent-SpawnDeathSquadEVAPreset = спавн бойца эскадрона смерти
    .desc = Спавн поинт бойца эскадрона смерти
    .suffix = CALLERT
callert-deathsquad-eva-name = Боец эскадрона смерти
callert-deathsquad-eva-desc = Уничтожитель всего живого.
callert-deathsquad-eva-rules = Ваша задача уничтожить станцию и ликвидировать весь персонал. Вы подчиняетесь ЦК.
