[net]
tickrate = 30
max_connections = 64
upnp = true

[game]
hostname = "[RU][MRP]СССП — Кто не работает, тот не ест."
desc = "Добро пожаловать на сервер «СССП — Кто не работает, тот не ест»! \nВ данный момент сервер находится в стадии активной разработки. Если вы обнаружите какие-либо ошибки или у вас есть предложения, пожалуйста, сообщите об этом нашей команде: \nВ репозитории GitHub проекта; \nИли на нашем Discord-сервере."
maxplayers = 32
map_rotation = true
peaceful_end = false
lobbyenabled = true
role_timers = false

[server]
rules_file = "USSPMRPRuleset"

[rules]
time = 15

[hub]
tags = "lang:ru,region:eu_e,rp:med"
advertise = true

[atmos]
space_wind = true

[movement]
mob_pushing = false

[admin]
see_own_notes = true

[viewport]
maximum_width = 26

[netres]
limit = 25.0

#Вебхуки, апи бота сюда не вводить!!!